name: Java CI with Gradle

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        name: Java ${{ matrix.java_version }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                java_version: ['8', '11', '17']
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v3
              with:
                  java-version: ${{ matrix.java_version }}
                  distribution: 'temurin'
            - name: Validate Gradle wrapper
              uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
            - name: Build with Gradle on Java ${{ matrix.java_version }}
              uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
              with:
                  arguments: build
